[package]
name = "xabe-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "llmxabe"
path = "src/main.rs"

[dependencies]
tracing.workspace = true
xabe-log.workspace = true
xabe-model.workspace = true
xabe-cache.workspace = true
xabe-sched.workspace = true
xabe-engine.workspace = true
xabe-cuda.workspace = true
xabe-gguf.workspace = true
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "sync", "time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokenizers = "0.22"
