[package]
name = "xabe-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tracing.workspace = true
xabe-log.workspace = true
xabe-model.workspace = true
xabe-gguf.workspace = true
xabe-cuda.workspace = true
cudarc = { version = "0.19.9", features = ["driver", "nvrtc", "fallback-dynamic-loading", "cuda-12040"] }
xabe-cache.workspace = true
xabe-sched.workspace = true
xabe-kernels.workspace = true
xabe-grammar.workspace = true
parking_lot.workspace = true
rustc-hash.workspace = true
half.workspace = true
smallvec = "1"

[dev-dependencies]
