[package]
name = "xabe-cuda"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
half.workspace = true
tracing.workspace = true
xabe-log.workspace = true
cudarc = { version = "0.19.9", features = ["driver", "nvrtc", "cublaslt", "f16", "fallback-dynamic-loading", "cuda-12040"] }
